Davide
Gio-Formichella/ElaboratoSWE pull request #10
Opened 2023-07-03 14:25 UTC by davidelomba

2023-07-03 16:02 UTC, Gio-Formichella requested changes
Va bene, va rinominato un paio di metodi per maggiore chiarezza e forse una modifica

2023-07-03 16:43 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public void addVisit_Booking(Visit v, Visitor vr, int code, int number_of_tickets) throws SQLException {
Questo chiamalo semplicemente addBooking

2023-07-03 16:44 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public ArrayList<Booking> get(int code) throws SQLException, ParseException {
Questo dovrebbe ritornare un Booking e non un array list di Bookings

2023-07-04 08:54 UTC, davidelomba commented on main/orm/BookingDAO.java
> +    public ArrayList<Object> getBookingVisit(int code, Visit v) throws SQLException, ParseException {
getBookedInfo è il nome del metodo nel VisitorController che richiama questo metodo. Per quanto riguarda i parametri, viene passata la visita perché voglio ritornare tutte la prenotazione ad una precisa visita... Però effettivamente con la modifica del db ad una prenotazione corrisponde una sola visita, quindi potrei evitare di passarla come parametro

2023-07-04 09:02 UTC, davidelomba commented on main/orm/BookingDAO.java
> +    public ArrayList<Booking> get(int code) throws SQLException, ParseException {
Giusto, con la modifica del db adesso ritorna un singolo booking

2023-07-04 13:33 UTC, Gio-Formichella approved these changes
Apposto per ora

2023-07-04 15:47 UTC, merged