fix di bug, nuovo metodo VisitDAO
Gio-Formichella/ElaboratoSWE pull request #12
Opened 2023-07-03 21:13 UTC by MichaelUnifi

Aggiunto un metodo utile al curator per la cancellazione di itinerari (valutare se mettere o no e se sì testare anche curator) con relativo test. Fix del bug di notifica per visite cancellate, prima veniva cancellata la visita e poi notificato, doveva essere il contrario

2023-07-04 13:24 UTC, Gio-Formichella requested changes
Aggiunta discussione sul metodo aggiunto. Trovato bug in modifyVisit già pushato, il metodo fa un update nel DB ma notifica i visitatori che la visita è stata cancellata

2023-07-04 13:24 UTC, Gio-Formichella commented on main/business_logic/Curator.java
>      public void cancelItinerary(Itinerary i) throws SQLException{
Questa operazione dovrebbe essere inclusa nel modifyVisit di BookingOffice

2023-07-04 13:41 UTC, Gio-Formichella commented
Inoltre farei dei test e darei un'occhiata ai DAO di Visit, tipo il metodo delete fa rimozione da tabella che non esiste più

2023-07-04 19:58 UTC, MichaelUnifi commented on main/business_logic/Curator.java
>      public void cancelItinerary(Itinerary i) throws SQLException{
nel senso che bookingoffice deve chiamare questa operazione?

2023-07-04 20:37 UTC, MichaelUnifi commented on main/business_logic/Curator.java
>      public void cancelItinerary(Itinerary i) throws SQLException{
ho fatto in modo che modificando una visita si modifichino le tuple in visit_itinerary (in effetti perché non l'ho fatto prima mi sfugge). Però ritengo sia necessario che anche curator quando rimuove itinerari debba chiamare il metodo del VisitDAO

2023-07-04 20:39 UTC, MichaelUnifi commented
Non ho capito a che tabella ti riferisci quando dici che in update non esiste più: modifica tuple in booking, visit e visit_itinerary, che ad oggi sono presenti del db. Fammi sapere

2023-07-05 08:19 UTC, Gio-Formichella commented
> Non ho capito a che tabella ti riferisci quando dici che in update non esiste più: modifica tuple in booking, visit e visit_itinerary, che ad oggi sono presenti del db. Fammi sapere

Git hub mi faceva vedere la versione vecchia di delete in cui c'era ancora visit_booking, nessun problema

2023-07-05 10:22 UTC, Gio-Formichella requested changes

2023-07-05 10:22 UTC, Gio-Formichella commented on main/orm/VisitDAO.java
> +    /*public void removeItineraryFromVisits(int id)throws SQLException{
Metodo da rimuove non da commentare, evitare "dead code" potenzialmente pericoloso per lo sviluppo

2023-07-05 10:22 UTC, Gio-Formichella commented on test/daos/VisitDAOTest.java
>      void removeItineraryFromVisits(){
Stessa cosa di sopra

2023-07-06 11:34 UTC, Gio-Formichella approved these changes

2023-07-06 11:35 UTC, merged