Aggiunti VisitorDao, BookingOffice e test
Gio-Formichella/ElaboratoSWE pull request #4
Opened 2023-06-26 21:23 UTC by MichaelUnifi

rimangono un paio di dubbi sul testing di viewVisits (toglierei senza implementare, fa solo molti getTransitive)
inoltre sul curator ho aggiunto qualcosa che mi sembrava utile (guardare TODO)
infine, mortacci vostri con il format date e time di sql ci ho smattato.
fatemi sapere se qualcosa non torna.

2023-06-27 07:48 UTC, Gio-Formichella requested changes
Ho aggiunto alcuni commenti sulle cose che non mi tornano, per il resto tutto bene

2023-06-27 07:48 UTC, Gio-Formichella commented on main/business_logic/BookingOffice.java
> +        if (nlsubscribers.size()>0){
Quando cancelli una visita dovrebbero essere notificati i visitatori che avevo una prenotazione per quella visita e non i nlsubscriber

2023-06-27 07:48 UTC, Gio-Formichella commented on main/business_logic/BookingOffice.java
> +    public void modifyVisit(Visit v) throws SQLException, ParseException{
Se viene modificata una visita dovrebbero essere notificati i visitatori che hanno una prenotazione per tale visita

2023-06-27 07:48 UTC, Gio-Formichella commented on main/business_logic/Curator.java
>      public void cancelItinerary(Itinerary i) throws SQLException{
Per come la vedo io ci sono 2 opzione: si lascia com'era (il curator rimuove un itinerario "sicuro": non appartiene a nessuna visita) oppure come hai fatto rimuove l'itinerario dalle visite ed in questo caso dovrebbe notificare i visitatori che avevano una prenotazione che conteneva l'itinerario rimosso

2023-06-27 07:48 UTC, Gio-Formichella commented on main/orm/VisitDAO.java
> +    public void delete(int code) throws SQLException {
dovrebbe anche eliminare l'associazione con booking in Visit_booking (Se fai il test vedi che viene violato il vincolo di FK del DB)

2023-06-27 07:48 UTC, Gio-Formichella commented on main/orm/VisitDAO.java
> +    public void update(Visit v) throws SQLException, ParseException {
se cambiato codice deve cambiare anche l'associazione con i booking in Visit_booking. Il codice potremmo anche far si che non cambi (non dà alcun vantaggio e complica solo le cose)

2023-06-30 18:21 UTC, MichaelUnifi commented on main/orm/VisitDAO.java
> +    public void update(Visit v) throws SQLException, ParseException {
comunque qui non mi sembra venga cambiato il codice, viene solo usato per trovare il valore nella query

2023-06-30 18:40 UTC, MichaelUnifi commented
credo di aver fatto tutto, fatemi sapere se mi è sfuggito qualcosa

2023-06-30 18:50 UTC, Gio-Formichella approved these changes
Perfetto, faccio il merge

2023-06-30 18:50 UTC, Gio-Formichella commented on main/business_logic/BookingOffice.java
> +    public void setVisit(int code, String date, String time, int maxVisitors, float price, ArrayList<Itinerary> itineraries) throws SQLException, ParseException{
Se riesci, dovrebbe controllare che la data inserita sia una data e la stessa cosa per il time (Non è essenziale programma funziona uguale)

2023-06-30 18:50 UTC, merged