Aggiunto il metodo viewBookings()
Gio-Formichella/ElaboratoSWE pull request #5
Opened 2023-06-27 10:20 UTC by davidelomba

Controllate che non ci siano errori

2023-06-27 11:01 UTC, Gio-Formichella commented
Magari dai un riformatta al codice per renderlo più bellino. Il merge nel main lo facciamo quando ci sono anche i test per essere sicuri di non trovare bug in futuro

2023-06-28 18:06 UTC, Gio-Formichella requested changes

2023-06-28 18:06 UTC, Gio-Formichella commented on main/business_logic/VisitorController.java
> +    public String printTicket(int code) throws SQLException, ParseException {
BookingDAO non ha un metodo di print ( si occupa solo di fornire ai controller gli oggetti del DB)

Non ritorna solo codice del biglietto ma anche informazioni relative al visitor prenotante , al pagamento del biglietto e magari le informazioni della visita

2023-06-28 18:06 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    static int new_code = 0;
Si era detto di mantenere manuale scelta del codice e su richiesta del prof inserire la logica di scelta nel programma (+facile estendere che rimuovere)

2023-06-28 18:06 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public void addVisit_Booking(Visit v, Visitor vr) throws SQLException {
Non ho capito perchè c'è sia un metodo add che uno di insert

2023-06-28 18:06 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public String print(int code) throws SQLException, ParseException {
Da rimuovere

2023-06-29 09:10 UTC, davidelomba commented on main/business_logic/VisitorController.java
> +    public String printTicket(int code) throws SQLException, ParseException {
Il metodo print ritorna una stringa con: nome, cognome, email del Visitor che ha prenotato, il codice della prenotazione, data e ora della visita e se ha pagato o meno. Non ho capito la prima frase... dove dovrei inserire questo metodo?

2023-06-29 09:13 UTC, davidelomba commented on main/orm/BookingDAO.java
> +    public void addVisit_Booking(Visit v, Visitor vr) throws SQLException {
Perché l'idea era che nel caso del bookVisit non venisse passato un oggetto Booking, ma venisse creato nel metodo add_VisitBooking (al contrario nell'insert(), molto utile per i test della delete() e get(), si occupa di inserire un oggetto Booking passato tra i parametri)

2023-06-29 09:14 UTC, davidelomba commented on main/orm/BookingDAO.java
> +    public String print(int code) throws SQLException, ParseException {
E' un metodo utilizzato per la creazione del biglietto (che io vedo come una stringa con tutte le informazioni utili)

2023-06-29 09:35 UTC, Gio-Formichella commented on main/business_logic/VisitorController.java
> +    public void bookVisit(Visit v, Visitor vr) throws SQLException{
Se non c'è ci dovrebbe essere

2023-06-29 09:49 UTC, Gio-Formichella requested changes

2023-06-29 09:49 UTC, Gio-Formichella commented on main/business_logic/VisitorController.java
> +    public String printTicket(int code) throws SQLException, ParseException {
ok, avevo capito male io, il metodo non fa un print ma ritorna le informazioni per il print. Magari rinominalo getTicketInfo o qualcosa di simile

2023-06-29 09:49 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public String print(int code) throws SQLException, ParseException {
Ok, avevo capito male. Invece di ritornare un string ritorna una lista con oggetti: Visitor; Visit, Booking

2023-06-29 09:49 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public void addVisit_Booking(Visit v, Visitor vr) throws SQLException {
Allora quello che farei è rimuoverei il metodo di insert e lo aggiungerei alla classe di test. è da evitare di avere metodi visibili nella interfaccia che non vogliamo siano utilizzati.

2023-06-29 13:40 UTC, davidelomba commented on main/orm/BookingDAO.java
> +    public void addVisit_Booking(Visit v, Visitor vr) throws SQLException {
Okk

2023-06-29 13:46 UTC, davidelomba commented on main/orm/BookingDAO.java
> +    public String print(int code) throws SQLException, ParseException {
Allora forse è un metodo che non serve dato che c'è già il metodo get() che restituisce una lista di Booking (ogni oggetto Booking ha come attributi un Visitor e una Visit, quindi tutte le informazioni utili sono già dentro di esso)

2023-06-29 16:54 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public String print(int code) throws SQLException, ParseException {
Sni, getBooking che magari rinominerei a getVisitorBooking"S" ritorna tutte le prenotazioni di un singolo utente, il controller ha bisogno di un metodo get ritorna una prenotazione specifica (ad esempio getBooking(Visitor, Visit) )

2023-06-29 17:08 UTC, Gio-Formichella commented on main/business_logic/VisitorController.java
> +    public ArrayList<Booking> getTicketInfo(int code) throws SQLException, ParseException {
Chiamalo getBookedTicketInfo. Due opzioni: o metodo ritorna singolo booking e allora servono metodi di getter per Visitor del Booking e Visit del booking con copia difensiva e quindi costruttore di copia nelle rispettive classi oppure fai si che il dao ritorni (Booking, VisitorDelBooking, VisitDelBooking ) (che non è un problema che tanto già lo deve fare) (il metodo del DAO è transitive)

2023-06-29 17:08 UTC, Gio-Formichella commented on main/orm/BookingDAO.java
> +    public int getBookedTickets(Visit v) throws SQLException {
Lo sposterei nel dao della visita perchè non istanzia Booking e usa un Visit

2023-06-30 08:46 UTC, davidelomba commented on main/orm/BookingDAO.java
> +    public String print(int code) throws SQLException, ParseException {
Sì e quello è il metodo get(). Inizialmente c'era il metodo get() che ritorna il Booking con il Visitor e la Visit collegati, il getBooking() (stessa cosa del get() solo che ritorna le prenotazioni di un solo Visitor) e poi print() che ritorna la stessa cosa di get() solo in formato stringa... Ho eliminato quest'ultimo

2023-06-30 09:13 UTC, davidelomba commented on main/business_logic/VisitorController.java
> +    public ArrayList<Booking> getTicketInfo(int code) throws SQLException, ParseException {
Non ritorna un solo Booking, ma un'arraylist di Booking perché alla stessa prenotazione possono essere collegate più visite. Nel secondo metodo che struttura dati potrei usare? Una semplice List()?

2023-07-03 14:24 UTC, closed without merging